// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_PpILGuWzyi2J-ic6pMmSRQpWPSxPamE',
    appId: '1:121997422841:web:6d027393ee9e9edc5f3228',
    messagingSenderId: '121997422841',
    projectId: 'bljrflutter',
    authDomain: 'bljrflutter.firebaseapp.com',
    storageBucket: 'bljrflutter.firebasestorage.app',
    measurementId: 'G-WY522R91YV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgC8-lGZbpBGSf5VfrP4C2JIaoAoFSDOk',
    appId: '1:121997422841:android:084908b1f38935425f3228',
    messagingSenderId: '121997422841',
    projectId: 'bljrflutter',
    storageBucket: 'bljrflutter.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClNimOakzjmL6-zzjF-KGmZ2HOvl68gBU',
    appId: '1:121997422841:ios:9f5926d3b15a99485f3228',
    messagingSenderId: '121997422841',
    projectId: 'bljrflutter',
    storageBucket: 'bljrflutter.firebasestorage.app',
    iosBundleId: 'com.example.bnccFinalProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyClNimOakzjmL6-zzjF-KGmZ2HOvl68gBU',
    appId: '1:121997422841:ios:9f5926d3b15a99485f3228',
    messagingSenderId: '121997422841',
    projectId: 'bljrflutter',
    storageBucket: 'bljrflutter.firebasestorage.app',
    iosBundleId: 'com.example.bnccFinalProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA_PpILGuWzyi2J-ic6pMmSRQpWPSxPamE',
    appId: '1:121997422841:web:8dc2233d8cd5630b5f3228',
    messagingSenderId: '121997422841',
    projectId: 'bljrflutter',
    authDomain: 'bljrflutter.firebaseapp.com',
    storageBucket: 'bljrflutter.firebasestorage.app',
    measurementId: 'G-GVP5HRVLMS',
  );

}